### ISSUE TITLE
How to tell if the route is signed or not (and if filtering peers only and or partially safe)?

### ISSUE THREAD

**Issue by tedtrp** [cloudflare/isbgpsafeyet.com#471]
#1 If an ISP signed a route, how does one tell that they did?

#2 And if they did sign the route: 

a) how does one know if it is with filtering peers only?

b) how does one know how safe it is? For example besides "unsafe" I see reports of "partially safe".

Please and thank you.

**Comment by lspgn** [comment]
Hi @tedtrp :
For 1.
The RPKI data is public, you can download it and parse it with RPKI validators (OctoRPKI, Routinator, rpki-client, FORT, RIPE RPKI validator) or use our public [dashboard](https://rpki.cloudflare.com/?view=bgp&prefix=&asn=13335). You can then search by ASN or directly the route. One thing to note, an owner of IP resources can sign to any ASN. A same route can have multiple signed records with different ASNs.

For 2.
This information is provided by the ISP regarding their configurations. And in some cases, looking at propagation of certain invalid routes and correlating with the ISP relationship can indicate partial filtering (eg: filtering of peers but not customers)
The difference between unsafe and partially safe is defined in [Contributing](https://github.com/cloudflare/isbgpsafeyet.com/blob/master/CONTRIBUTING.md). We changed the definition since the launch and we don't accept signed as partially safe anymore (we only changed the ISPs' classification on the newly added).

**Comment by tedtrp** [comment]
Ok.

What if the ISP has both signed and unsigned?

As an example my ISP (3737) has both. 198.182.247.0/24 and 209.102.224.0/20 are unsigned but everything else is.

Please and thank you

**Comment by lspgn** [comment]
While it would be optimal to sign everything, some IP space cannot always be signed (eg: legacy, delegated, doing a transfer).
In the case of PenTeledata AS3737, 94% of their routes are signed. Which is definitely fine. We're trying to avoid some ISPs that have too sparsely signed prefixes.
I had a look at `198.182.247.0/24`, it seems that our BGP collector used behind rpki.cloudflare.com missed the withdrawals from 3737 (currently announced by AS6128).
The ROA probably will be created soon?
![Screen Shot 2020-09-09 at 3 08 25 PM](https://user-images.githubusercontent.com/27725238/92660207-d6312e00-f2ae-11ea-8983-3b0d4da92614.png)

**Comment by tedtrp** [comment]
Where did you get that graph from?

Please and thank you

**Comment by lspgn** [comment]
@tedtrp from [RIPE Stat](https://stat.ripe.net/widget/routing-history#w.resource=198.182.247.0%2F24).

**Comment by lspgn** [comment]
1. & 2. Yes, feel free to make the change to "signed" in that case. "started" would also mean the ISP is working towards RPKI Origin Validation. You can use GitHub editor to edit the specific line. Similar to the previous changes.
3. Usually this information is given by the ISP. Otherwise, you would need to find if you can reach invalid routes from Cloudflare _and_ customers of PenTeleData (eg: on [bgpview](http://bgpview.io/asn/3737#downstreams-v4)). Nothing that would be easy to test from a web based UI as far as I know. This would require lots of traces.

(one side note: try not using # followed by a number on GitHub comments, this references another issue which can be unrelated. [example](https://github.com/cloudflare/isbgpsafeyet.com/pull/3#ref-issue-696256394))

**Comment by tedtrp** [comment]
For the side note:

Q1 Instead of # and number use # letter and then number(s) - like I am now?

Q2 Who thought of that idea of using # followed by a number to ref another issue? 

Q3 Why did they think that is a good idea? 

Q4 What where they thinking?

Q5: Was that feature added before or after MS take ownership of this platform?

Please and thank you

**Comment by lspgn** [comment]
q1: a) -> no need for too much details since it has to fit in the table on the page.

q2: yes this is fine. GitHub can also format as a list automatically when you write `1.`

q3: I don't know :p https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls

q4: it's very common in code repositories to have this kind of referencing

q6: this feature has been here for a while, definitely before Microsoft

**Comment by tedtrp** [comment]
While I re-edited my post, ok, 

PenTeleData,ISP,signed,unsafe,3737,1071" it is..

**Comment by lspgn** [comment]
👍  will check for your pull request when it's ready

**Comment by tedtrp** [comment]
Changed to "PenTeleData,ISP,virtually signed,unsafe,3737,1071" If you do not like it fine, change it to "PenTeleData,ISP,signed,unsafe,3737,1071" :)

**Comment by lspgn** [comment]
I'd prefer "signed" so that it remains consistent with the other records

**Comment by tedtrp** [comment]
Ok, fine changed

**Comment by tedtrp** [comment]
Closing because there is nothing else I need to ask
